### ISSUE TITLE
Suppress events

### ISSUE THREAD

**Issue by ashmastaflash** [cloudpassage/don-bot#20]
Use an environment variable to define a comma-separated list of event types that should not appear in-channel.  For example: if `SUPPRESS_EVENTS_IN_CHANNEL="sca_rule_failed,vulnerable_software_package_found_on_image"` is set, then donbot will not put these events in the Slack channel.  This does not affect events that trigger quarantine or IP blocker.

**Comment by mong2** [comment]
we are currently only showing events that are critical. Do we want to give user the option to print both critical/non-critical? and another option for SUPRESS_EVENTS_IN_CHANNEL?

**Comment by ashmastaflash** [comment]
No, we just want to give the customer the ability to suppress certain critical events.

**Comment by mong2** [comment]
v0.17.3
