### ISSUE TITLE
donbot tell me about group xyz reports issues

### ISSUE THREAD

**Issue by ashmastaflash** [cloudpassage/don-bot#29]
The group report provided by donbot should report the issues for the group, as well as the number of hosts within the group affected by each issue.

Server issues look like this:

```
Issue:
    Type:     csm
    ID:       blahblah
    Status:   active
    Critical: True
    Rule key: csm::2811407::V-71905 When passwords are changed or new passwords are established, the new password must contai...
    Created:  2018-03-04T02:57:19.932Z
```

Group issues should look like this:

```
Issue:
    Servers affected: 9
    Type:     csm
    Status:   active
    Critical: True
    Rule key: csm::2811407::V-71905 When passwords are changed or new passwords are established, the new password must contai...
    First seen:  2018-03-04T02:57:19.932Z
    Last seen:  2018-03-04T02:57:19.932Z
```

When printing in the `tell me about group xyz` response, issues should be grouped by criticality (critical first) and ordered by the number of affected servers.

**Comment by eatwithforks** [comment]
https://github.com/cloudpassage/halocelery/pull/13.

agreed to remove status, first seen, and last seen.
